permalink: /:categories/:year/:month/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author:
  name: Yicong Chen
  email: chen.yicong@outlook.com
#  link: http://painterlin.com
  github: https://github.com/Yc-Chen
#  music: http://soundcloud
  linkedin: https://nl.linkedin.com/in/yicong-chen-37245759

# 站点信息
title: Yicong Chen's(陈益聪) Blog
description: Yicong Chen's professional blog
url: http://yc-chen.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/cong2.png
favicon: /public/img/cong2.png

# google analytics 设置 (To see who visited your sebwite and how)
ga:
  id: UA-73303707-1
  url: yc-chen.github.com

# disqus 设置(comment system)
disqus:
  shortname: yc-chen
  id: yicongchen

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
#cates:
#  - Optimization
#  - LaTeX

# 中文本地化(标签)
locals:
  tags: Tags
  about: About
  newest: Latest
  archive: Archive
